### ISSUE TITLE
How to add new controllers doc

### ISSUE THREAD

**Issue by felipebueno** [adonaac/thomas#9]
Hi, @adonaac 

Can you document how to add support for new controllers, please? I own a generic Multilaser joystick and I'd like to use it to play test my game. I'm on OS X.

Thanks in advance! :smile:

**Comment by a327ex** [comment]
I haven't added that feature yet. But what you wanna do is add the controller settings to gamecontrollerdb.txt (you can see how to generate the settings [here](https://github.com/gabomdq/SDL_GameControllerDB)) and then call love.joystick.setGamepadMappings('gamecontrollerdb.txt'). This should make it so that the settings you added to the file will be read by LÖVE and that will make your controller work.
